### Variables
@host = http://localhost:3000
@token = TU_TOKEN_JWT_AQUI

### 1. Chequeo de Salud
GET {{host}}/salud

### 2. Registro de Usuario Normal
POST {{host}}/auth/registro
Content-Type: application/json

{
  "nombre": "Crash Bandicoot",
  "email": "crash@wumpa.com",
  "password": "Password123!"
}

### 3. Login de Usuario
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "jugador@retroquest.com",
  "password": "AdminPass123!"
}

### 4. Obtener mis juegos
GET {{host}}/juegos
Authorization: Bearer {{token}}

### 5. Crear juego
POST {{host}}/juegos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "titulo": "Metroid Prime",
  "plataforma": "GameCube",
  "estado": "Jugando",
  "horas_jugadas": 5,
  "rating": 5
}

### 6. Ruta Admin
GET {{host}}/admin/estadisticas
Authorization: Bearer {{token}}

### PRUEBAS DE SEGURIDAD QUE DEBEN FALLAR:

### Caso Falla 1: Inyección SQL
POST {{host}}/auth/login
Content-Type: application/json

{
  "email": "admin@retroquest.com' OR '1'='1",
  "password": "password"
}

### Caso Falla 2: Sin Token (401)
GET {{host}}/juegos

### Caso Falla 3: Input Inválido (400)
POST {{host}}/juegos
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "horas_jugadas": 10
}